### ISSUE TITLE
Coordinate development with other contributors

### ISSUE THREAD

**Issue by skddc** [Raindeer44/restore#1]
Hi there,

I just accidentally found this fork by browsing the network graph of the original repo. It's really cool that you've been working on this! Especially updating the code to modern JS is a great idea imo.

I noticed it's not using the improvements from [@lesion's fork](https://github.com/lesion/restore), probably because you missed that one (which is easy, as GitHub is hiding that network graph pretty well these days).

Unfortunately, the original author doesn't seem interested in coordinating any development efforts by other contributors, so I think it would be great if you and @lesion could maybe at least coordinate your changes, and maybe we could have a new shared repo with a different name that links back to the original, but that can also serve as an entry point for any future users and contributors.

What do you think?

/cc @lesion

**Comment by lesion** [comment]
thanks @skddc for your effort!
I didn't notice this fork neither, and I think it's good to refresh the original code.
I think we can host this project under the remoteStorage.js umbrella?

**Comment by skddc** [comment]
If you're both ok with it, I could create a repo in the @remotestorage organization and give you both ownership rights. I really think we should choose a different name though.

**Comment by lesion** [comment]
I'm ok with this.
Feel free to assign a different name.

**Comment by skddc** [comment]
That would be for you guys to choose I guess. Let's wait for @Raindeer44 to let us know what he thinks in the first place.

**Comment by Raindeer44** [comment]
Hi guys! This sounds like a great idea I'd love to be a part of! I had originally made this fork to try to reduce dependencies and hopefully even improve performance, and then use it in another project I was thinking about. However I had some day job commitments that got in the way and I never got to this, and you're right I never saw @lesion's fork. But yeah this is a good idea!

For a name, I agree it should change, but I don't have any ideas at the moment...

**Comment by skddc** [comment]
Hooray! Great to hear. Let's get the ball rolling then...

Regarding the name, here's some brainstorming:

* rs-server.js -- boring, forgettable
* reServe -- sounds a bit weird to me
* armadietto -- Italian for "locker" as far as Google Translate tells me
* node-remotestorage -- a bit boring, but would be clear that it's a node.js program

**Comment by Raindeer44** [comment]
- I was never a big fan of reStore because it is one capitalization off from restore, possibly implying it's a recovery software. I feel similar about reServe (and reserve). 

- node-remotestorage is straight to the point, but I agree it's boring.

- armadietto is fun, I kinda like it

A couple more ideas:

- rServe.js -- also sounds kinda off, but avoids the 'reserve' thing

- davey.js -- because Davey Jones' Locker? :man_shrugging: 

I want to have an idea involving a Greek or Roman god, but I can't think of anything.

**Comment by lesion** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

armadietto makes me laugh :rofl:
I would say let's go with it.

**Comment by skddc** [comment]
I guess we have a winner. :)

I created an empty repo and gave you both admin access: https://github.com/remotestorage/armadietto/

**Comment by Raindeer44** [comment]
I think maybe we should start with a clone of @lesion's fork and go from there?

Originally when I created my fork, my first goal was to replace the [async](https://www.npmjs.com/package/async) dependency with modern vanilla JS, so I'd love to start looking at that later today.

**Comment by lesion** [comment]
I'll push a branch with your merge in a while

**Comment by lesion** [comment]
Ok, I've done, let's move this discussion somewhere else?
`armadietto` is currently not working due to usage of unclear (to me) `domain` feature (that I see is deprecated: https://nodejs.org/api/domain.html).
So @Raindeer44 if you want to check it out, you're welcome.
